language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25

before_install:
  - export ANDROID_HOME=/usr/local/android-sdk
  - wget https://dl.google.com/android/repository/android-ndk-r14-linux-x86_64.zip
  - unzip -q android-ndk-r14-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r14
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties

script:
  - ./gradlew build
