language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-25

before_install:
  - export ANDROID_HOME=/usr/local/android-sdk
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip -O ndk.bin
  - 7z x ndk.bin > /dev/null
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r13b
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties

script:
  - ./gradlew build connectedCheck
