language: android
jdk: oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - export ANDROID_HOME=/usr/local/android-sdk

  - wget https://dl.google.com/android/repository/android-ndk-r14-linux-x86_64.zip
  - unzip -q android-ndk-r14-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r14
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties

  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew build
